### ISSUE TITLE
Faltaría una comparación para adecuar la expresión

### ISSUE THREAD

**Issue by hipema** [iesgrancapitan-entornos/2019-20-practica-5-github-issues-przdavid#1]
https://github.com/iesgrancapitan-entornos/2019-20-practica-5-github-issues-przdavid/blob/f3bc0d65773a6e53e6cb619dfd80fe49aa2092a4/ejercicio11.py#L34

Creo que  en esta línea haría falta incluir la comparación entre el lado B con el C:

if (ladoA == ladoB and ladoA != ladoC or ladoB == ladoC and ladoA != ladoB or ladoA == ladoC and ladoA != ladoB):

**Comment by przdavid** [comment]
Tienes razón. ¡Gracias!

**Comment by jaimerabasco** [comment]
Falta asignarte el Issue @przdavid 
Cierralo después
