### ISSUE TITLE
Detalle en documentación

### ISSUE THREAD

**Issue by hipema** [iesgrancapitan-entornos/2019-20-practica-5-github-issues-przdavid#2]
https://github.com/iesgrancapitan-entornos/2019-20-practica-5-github-issues-przdavid/blob/e0e8f68862cc715cef1e991b8eb74bf654d14e31/ejercicio11.py#L4

Para el autor normalmente se recomienda  @author ,  para la fecha utilizar @since y para la fecha @date, también incluiría @version para referenciar la versión del programa por si sufriese futuras mejoras.

**Comment by przdavid** [comment]
Suena interesante. Lo tendré en cuenta.
