### ISSUE TITLE
Letra Ñ

### ISSUE THREAD

**Issue by hipema** [iesgrancapitan-entornos/2019-20-practica-5-github-issues-przdavid#3]
https://github.com/iesgrancapitan-entornos/2019-20-practica-5-github-issues-przdavid/blob/573c6a051999174602cd93b7743ffd49a15739fd/ejercicio13.py#L31-L34

Creo que podría ser interesante añadir la letra Ñ, ya que es bastante frecuente en nuestro idioma

**Comment by przdavid** [comment]
¡Buena idea!
